"""including profile picture type column

Revision ID: c41aa1ede1ac
Revises: 5fcc528fd78c
Create Date: 2024-07-08 16:47:06.941102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41aa1ede1ac'
down_revision = '5fcc528fd78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_type')
    # ### end Alembic commands ###
